language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm
- npm install -g grunt-cli
after_script:
- grunt codacy
before_deploy: grunt dist
deploy:
- provider: releases
  api_key:
    secure: R3gL1QxHmxzwlKtLuGOnvuETMEGe7XUAfBJpFqYBEVBbMQVzu7f7j8r6qsQvHaazsclZHviNnaGrggY4InCyTa0DQ8/2/QIVpg0VSPK1i2k3ALJkfsP/ap4wG4vudzVWX6UPf+6Y8fNW9KAvJE7VQT3IGhxdarpuC12TWEl/hnrK7xogeG1T1a/SRzUlEYCNdMSbWIx9VVAeZvx/F+8DUI17OvYUUi1ADmphtEHOba9QLmm8gXlNFS2uuW0e+TjCFwhqk31rzjyUTcMsugX/ZI7QnBE/aWpHBr4EurVF0S+CDJkaEPLcNYHsBmF4K6JZZDsq7n5UHmSboIoDLAcdDmIHMYMyN1JBA4qUt3fHvQ9hAQprSjbY3Om30leGYb83GGYyzEFl4Kl9tXxlHCKMj3ftjz4+W7dEusUglfJwAoRx941bJMa/HEMMyBf2x8WZpNHodEf27fm10+IN5LPngzXgxFVENAeLPNKQaCUOxUyPwCcD0txqOZdIAzKLUFoP1t4P+Zr8nFdaYcc4+ZzpUQokNXMPMEA95aamPWo/9QCikEtkT9f2UH5EWfLmbyYl69StiY3Uxj6CNTa0QTs9vYMlRIgg9jELfjvsD83luXylVKwLJ8xLnSjM2iBlW8jhINNLwmY3k6VIVrcFN7X3Ma/Hmqw3IpvWoAT3YayeipE=
  skip_cleanup: true
  file: layout-grid.zip
  on:
    repo: clippings/layout-grid
    tags: true
- provider: npm
  email: ikerin@gmail.com
  skip_cleanup: true
  api_key:
    secure: qv4djinToo2F4HF81FwZz9ShSwuggfQSlcIZS62Nyw10KNjYT5Nkbox+kHJWfXi9IFauFc+HkskhjJiVQrRypP5nKGmQSPHJGmEE1j71lKEKCc39P2tk6fiG20C/yLFnN/zPVfOE6s0iQ5JZqMCOsInpLQegSw197z4RNN1SW8upjethl+7FLXWnZRc35uEPUW2jB/CPVZ2kwpBZPS6RKCl16C2do4zZnUuqgGjYQoBKX6oXAiU4Q0FCaDednWV9CVQ5bNr5Rpj8Qi+rKB1tT3ffOCq+Vb9cLhX933pbCmDD9o4NKg1Adf7vc4z/nA340ElK+SphXbEwvKrrCbvIx2648zi5gjgoQBIhulZTWoA4Mqi8rMgIvvYdAlAqxeWXKnc9uQnP/LCe1Tz0ds6a8xrNuxz6scLN4S9W3/5R0hIc7GKxwFKTC9YbeQpdZ0vwx1KX1vHQ2o9n7t6r8/HX22+YOoE4N2wfOoObKIMLMT+vh5fIDdVcYqZ2lMaeiF4xZZurijuP9H/tZV5s54gSyPerZDB4EJhlV5dqFAmVZJ4f/RxkTKt/5/0bgJAmYsgcL4Xllbr6zkSynVlvUrodzmBBk1i6Ej33CqMVp+g4PMkrL3uckYpdByg2cqzcaRuco8CP6mTrOZ+SAOZQVabaVmEt5Bnlcw6cozj5wkmles4=
  on:
    repo: clippings/layout-grid
    tags: true
