language: node_js

cache:
  directories:
    - node_modules

before_install:
  - npm install -g grunt-cli

after_script:
  - node_modules/codeclimate-test-reporter/bin/codeclimate.js < build/lcov.info
